=== Anshu-Jain/simulap-plugin-sip/rpm/opt/simulap_manager/simulap/simulap-jmeter-sip/dictionnaries/SipHeaderXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           targetNamespace="http://www.hp.com/simulap/sip"
           xmlns:tns="http://www.hp.com/simulap/sip"
           xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.0"
           xmlns="http://www.hp.com/simulap/sip/headers"
           elementFormDefault="unqualified">
    
    <!-- This schema gathers user group related data structures. -->
    
	<xs:annotation>
		<xs:appinfo>
			<jaxb:schemaBindings>
				<jaxb:package name="com.hp.simulap.sip.headers" />
			</jaxb:schemaBindings>
		</xs:appinfo>
	</xs:annotation>
	
	<!--=================-->
	<!-- Schemas imports -->
	<!--=================-->
	
	<!--======================-->
	<!-- Element declarations -->
	<!--======================-->
	
	<!--===================-->
	<!-- Type declarations -->
	<!--===================-->
	
	<xs:element name="headers" type="tns:headerList"></xs:element>
	
	<xs:complexType name="headerList">
	<xs:sequence>
		<xs:element name="headerelem" type="tns:header" maxOccurs="unbounded" />
	</xs:sequence>
	</xs:complexType>
	
	<!-- This is the definition of the user group type. -->
	<xs:complexType name="header">
    	<xs:annotation>
    		<xs:appinfo>
    			<jaxb:class>
    				<jaxb:javadoc>
    				<![CDATA[
This defines a SIP header.
    				]]></jaxb:javadoc>
    			</jaxb:class>
    		</xs:appinfo>
    	</xs:annotation>
				<xs:sequence>
					<xs:element name="headerName" type="xs:string"/>
					<xs:element name="headerType" type="xs:string"/>
					<xs:element name="headerValue" type="xs:string"/>
				</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== Anshu-Jain/simulap-plugin-sip/rpm/opt/simulap_manager/simulap/simulap-jmeter-sip/dictionaries/SipHeadersGUIDictionary.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:headers xmlns:tns="http://www.hp.com/simulap/sip" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.hp.com/simulap/sip SipHeaderXMLSchema.xsd ">
		<headerelem> <headerName>Allow</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Allow-Events</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Authentication-Info</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Authorization</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Call-ID</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Call-Info</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Contact</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Content-Disposition</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Content-Encoding</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Content-Language</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Content-Length</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Content-Type</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>CSeq</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Date</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Error-Info</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Event</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Expires</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>From</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>In-Reply-To</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Join</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Max-Forwards</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>MIME-Version</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Min-Expires</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Min-SE</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Organization</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>P-Called-Party-ID</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>P-Access-Network-Info</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>P-Asserted-Identity</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>P-Asserted-Service</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>P-Associated-URI</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>P-Charging-Function-Addresses</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>P-Charging-Vector</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>P-Media-Authorization</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>P-Preferred-Identity</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>P-Preferred-Service</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>P-Profile-Key</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>P-Served-User</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>P-User-Database</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>P-Visited-Network-ID</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Path</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Priority</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Privacy</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Proxy-Authenticate</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Proxy-Authorization</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Proxy-Require</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>RAck</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Reason</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Record-Route</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Referred-By</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Replaces</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Reply-To</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Request-URI</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Require</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Retry-After</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Route</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>RSeq</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Security-Client</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Security-Server</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Security-Verify</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Server</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Service-Route</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Session-Expires</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>SIP-ETag</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>SIP-If-Match</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Subject</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Subscription-State</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Supported</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Timestamp</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>To</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Unsupported</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>User-Agent</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Via</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>Warning</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
		<headerelem> <headerName>WWW-Authenticate</headerName> <headerType>UTF8String</headerType> <headerValue></headerValue> </headerelem>
</tns:headers>
